import 'package:snapgo/models/best_time_info.dart';
import 'package:snapgo/models/spot_entity.dart';

class MockData {
  static List<SpotEntity> getSpots() {
    final now = DateTime.now();

    return [
      SpotEntity(
        id: '1',
        name: 'Nhà Thờ Đức Bà Sài Gòn',
        description:
            'Công trình kiến trúc Gothic nổi tiếng, biểu tượng của Sài Gòn với hai tháp chuông cao vút. Nơi lý tưởng để check-in và tìm hiểu về lịch sử văn hóa.',
        imageUrls: [
          'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800',
          'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800',
        ],
        latitude: 10.7797,
        longitude: 106.6991,
        address: '01 Công xã Paris, Bến Nghé',
        district: 'Quận 1',
        city: 'TP. Hồ Chí Minh',
        categories: ['Tôn giáo', 'Kiến trúc', 'Lịch sử'],
        tags: ['Check-in', 'Gothic', 'Biểu tượng'],
        bestTime: BestTimeInfo(
          description: 'Buổi sáng sớm hoặc chiều tà',
          months: ['1', '2', '3', '11', '12'],
          timesOfDay: ['Sáng', 'Chiều'],
        ),
        ratingAverage: 4.7,
        ratingCount: 2840,
        ratingBreakdown: {5: 2100, 4: 580, 3: 120, 2: 30, 1: 10},
        checkInCount: 15420,
        views: 45680,
        favorites: 3240,
        shares: 890,
        trendingScore: 9500,
        createdAt: now.subtract(Duration(days: 2)),
        updatedAt: now.subtract(Duration(hours: 5)),
        createdBy: 'user_saigon_explorer',
        isVerified: true,
      ),
      SpotEntity(
        id: '2',
        name: 'Chợ Bến Thành',
        description:
            'Khu chợ truyền thống lâu đời nhất Sài Gòn, nơi hội tụ ẩm thực đường phố, quà lưu niệm và văn hóa địa phương. Điểm đến không thể bỏ qua cho du khách.',
        imageUrls: [
          'https://images.unsplash.com/photo-1528127269322-539801943592?w=800',
          'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
        ],
        latitude: 10.7723,
        longitude: 106.6981,
        address: 'Lê Lợi, Phường Bến Thành',
        district: 'Quận 1',
        city: 'TP. Hồ Chí Minh',
        categories: ['Chợ', 'Ẩm thực', 'Mua sắm'],
        tags: ['Truyền thống', 'Ẩm thực', 'Lưu niệm'],
        bestTime: BestTimeInfo(
          description: 'Sáng sớm để tránh đông',
          months: [
            '1',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '10',
            '11',
            '12'
          ],
          timesOfDay: ['Sáng', 'Trưa'],
        ),
        ratingAverage: 4.3,
        ratingCount: 5620,
        ratingBreakdown: {5: 3200, 4: 1800, 3: 450, 2: 120, 1: 50},
        checkInCount: 28340,
        views: 67890,
        favorites: 4560,
        shares: 1230,
        trendingScore: 8900,
        createdAt: now.subtract(Duration(days: 5)),
        updatedAt: now.subtract(Duration(hours: 12)),
        createdBy: 'user_foodie_hcm',
        isVerified: true,
      ),
      SpotEntity(
        id: '3',
        name: 'Bitexco Financial Tower - Skydeck',
        description:
            'Tòa nhà cao nhất Sài Gòn với đài quan sát 360 độ ở tầng 49. Ngắm toàn cảnh thành phố lung linh về đêm, trải nghiệm đáng nhớ.',
        imageUrls: [
          'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800',
          'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800',
        ],
        latitude: 10.7715,
        longitude: 106.7038,
        address: '36 Hồ Tùng Mậu, Bến Nghé',
        district: 'Quận 1',
        city: 'TP. Hồ Chí Minh',
        categories: ['Cao ốc', 'View', 'Giải trí'],
        tags: ['Skydeck', 'Tầng cao', 'View đẹp'],
        bestTime: BestTimeInfo(
          description: 'Chiều tối để ngắm hoàng hôn và đêm',
          months: ['1', '2', '3', '11', '12'],
          timesOfDay: ['Chiều', 'Tối'],
        ),
        ratingAverage: 4.6,
        ratingCount: 3450,
        ratingBreakdown: {5: 2400, 4: 850, 3: 150, 2: 40, 1: 10},
        checkInCount: 12680,
        views: 38950,
        favorites: 2890,
        shares: 765,
        trendingScore: 9200,
        createdAt: now.subtract(Duration(days: 1)),
        updatedAt: now.subtract(Duration(hours: 3)),
        createdBy: 'user_sky_lover',
        isVerified: true,
      ),
      SpotEntity(
        id: '4',
        name: 'Phố Đi Bộ Nguyễn Huệ',
        description:
            'Con đường đi bộ sầm uất nhất Sài Gòn với nhiều sự kiện văn hóa, nghệ thuật đường phố. Không gian lý tưởng để dạo chơi, chụp ảnh và thưởng thức cafe.',
        imageUrls: [
          'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
          'https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800',
        ],
        latitude: 10.7743,
        longitude: 106.7009,
        address: 'Đường Nguyễn Huệ',
        district: 'Quận 1',
        city: 'TP. Hồ Chí Minh',
        categories: ['Phố đi bộ', 'Giải trí', 'Văn hóa'],
        tags: ['Sự kiện', 'Check-in', 'Cafe'],
        bestTime: BestTimeInfo(
          description: 'Buổi tối và cuối tuần',
          months: ['1', '2', '3', '4', '5', '10', '11', '12'],
          timesOfDay: ['Chiều', 'Tối'],
        ),
        ratingAverage: 4.5,
        ratingCount: 6780,
        ratingBreakdown: {5: 4200, 4: 2000, 3: 450, 2: 100, 1: 30},
        checkInCount: 45890,
        views: 92340,
        favorites: 7650,
        shares: 2340,
        trendingScore: 9800,
        createdAt: now.subtract(Duration(days: 3)),
        updatedAt: now.subtract(Duration(hours: 8)),
        createdBy: 'user_street_walker',
        isVerified: true,
      ),
    ];
  }
}
