// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUQDPSO93F8OemFFwgrBMGpHdWIZZb1IM',
    appId: '1:9661354500:web:1b9c1c7c6593d7da175b51',
    messagingSenderId: '9661354500',
    projectId: 'snapgo-4767a',
    authDomain: 'snapgo-4767a.firebaseapp.com',
    storageBucket: 'snapgo-4767a.firebasestorage.app',
    measurementId: 'G-N9R8CL7TJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbrzC7KGWfi9be7nJHsMRigiTSr4yoTc',
    appId: '1:9661354500:android:3123fccfc16f09c8175b51',
    messagingSenderId: '9661354500',
    projectId: 'snapgo-4767a',
    storageBucket: 'snapgo-4767a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxpW7du-GcB56b_hl6OdpX76HzWdx7Yx8',
    appId: '1:9661354500:ios:eb093978dfac29a9175b51',
    messagingSenderId: '9661354500',
    projectId: 'snapgo-4767a',
    storageBucket: 'snapgo-4767a.firebasestorage.app',
    iosBundleId: 'com.example.snapgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxpW7du-GcB56b_hl6OdpX76HzWdx7Yx8',
    appId: '1:9661354500:ios:eb093978dfac29a9175b51',
    messagingSenderId: '9661354500',
    projectId: 'snapgo-4767a',
    storageBucket: 'snapgo-4767a.firebasestorage.app',
    iosBundleId: 'com.example.snapgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUQDPSO93F8OemFFwgrBMGpHdWIZZb1IM',
    appId: '1:9661354500:web:a433480f1257895d175b51',
    messagingSenderId: '9661354500',
    projectId: 'snapgo-4767a',
    authDomain: 'snapgo-4767a.firebaseapp.com',
    storageBucket: 'snapgo-4767a.firebasestorage.app',
    measurementId: 'G-MD0515SZNE',
  );
}
